// <auto-generated />
namespace EX.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreditCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreditCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201708220014346_CreditCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
